dist: focal
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
      - libpng-dev
      - libsdl2-dev
      - portaudio19-dev
      - imagemagick
  homebrew:
    packages:
      - sdl2
      - libpng
      - tidy-html5
      - graphicsmagick
    update: true

before_script:
  - ./configure ${CONFIG}
script:
  - make -j$(nproc) && ctest -j$(nproc)

matrix:
  include:

    - env:
        - CONFIG="--enable-osx-bundle --disable-winuae-cpu --enable-debug"
      os: osx
      osx_image: xcode10
      compiler: clang

    - env:
        - CONFIG="--enable-osx-bundle --enable-winuae-cpu --enable-debug"
      os: osx
      osx_image: xcode12
      compiler: clang

    - env:
        - CONFIG="--disable-winuae-cpu --enable-werror --enable-debug"
      arch: arm64

    - env:
        - CONFIG="--enable-winuae-cpu --enable-werror --enable-debug"
      arch: ppc64le
      script:
        - make -j4 && ctest -j$(nproc)

    - env:
        - CONFIG="--enable-winuae-cpu --enable-werror --enable-debug"
      arch: s390x

    - env:
        - CONFIG="--disable-winuae-cpu --enable-small-mem --enable-werror"
      compiler: clang
